config/routes.rb
Rails.application.routes.draw do
  devise_for :property_owners
  root to: 'home#index'
  resources :properties, only: [:show, :new, :create] do
    get 'my_properties', on: :collection
  end
  resources :property_types, only: [:show, :new, :create]
  resources :property_locations, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :property_type
  belongs_to :property_location
  belongs_to :property_owner

  validates :title, :description, :rooms, :bathrooms, :daily_rate,
            presence: true
  validates :rooms, :bathrooms, :daily_rate, numericality: { greater_than: 0 }
end

app/models/property_location.rb
class PropertyLocation < ApplicationRecord
  has_many :properties
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/property_owner.rb
class PropertyOwner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :properties
end

app/models/property_type.rb
# coding: utf-8
class PropertyType < ApplicationRecord
  has_many :properties
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @properties = Property.all
    @property_types = PropertyType.all
    @property_locations = PropertyLocation.all
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_property_owner!, only: [:create, :new]
  def show
    @property = Property.find(params[:id])
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(
      params.require(:property).permit(
        :title, :description, :rooms, :bathrooms, :pets,
        :parking_slot, :daily_rate, :property_type_id, :property_location_id
      )
    )
    @property.property_owner = current_property_owner
    if @property.save
      redirect_to @property
    else
      render action: 'new'
    end
  end

  def my_properties
    @properties = current_property_owner.properties
  end
end

app/controllers/property_locations_controller.rb
class PropertyLocationsController < ApplicationController
  def new
    @location = PropertyLocation.new
  end

  def create
    @location = PropertyLocation.new(params.require(:property_location).permit(:name))
    if @location.save
      redirect_to root_path
    else
      flash.now[:alert] = @location.errors.messages
      render action: 'new'
    end
  end

  def show
    @property_location = PropertyLocation.find(params[:id])
  end
end

app/controllers/property_types_controller.rb
class PropertyTypesController < ApplicationController
  def new
    @property_type = PropertyType.new
  end

  def create
    @property_type = PropertyType.new(params.require(:property_type).permit(:name))
    if @property_type.save
      redirect_to root_path
    else
      # flash.now[:alert] = @p_t.errors.messages
      render action: 'new'
    end
  end

  def show
    @property_type = PropertyType.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<nav>
	<%= link_to 'Cadastrar Tipos de Imoveis', new_property_type_path %> |
	<%= link_to 'Cadastrar Região', new_property_location_path %>
</nav>

<div>
	<% @properties.each do |p| %>
		<%= link_to(p.title, property_path(p.id)) %>
		<%= p.description %>
		Quartos: <%= p.rooms%>
	<% end %>
	<% if @properties.empty? %>
		<%= 'Nenhum imóvel disponível' %>
	<% end %>
</div>
<div>
	<h4>Tipos de Imóveis:</h4>
	<nav>
		<ul>
			<% @property_types.each do |property_type| %>
				<li><%= link_to property_type.name, property_type %></li>
			<% end %>
		</ul>
	</nav>
</div>
<div>
	<h4>Regiões:</h4>
	<nav>
		<ul>
			<% @property_locations.each do |property_location| %>
				<li><%= link_to property_location.name, property_location %></li>
			<% end %>
		</ul>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <h1>Flats</h1>
	  <h3>Boas vindas ao sistema de locação de apartamentos</h3>
	  <nav>
		  <% if property_owner_signed_in? %>
			  <ul>
			  <li><%= link_to 'Cadastrar Imóvel', new_property_path %></li>
			  <li><%= current_property_owner.email %></li>
			  <li><%= link_to 'Meus Imóveis', my_properties_properties_path %></li>
			  <li><%= link_to 'Logout', destroy_property_owner_session_path, method: :delete %></li>
			  </ul>
		  <% else %>
			  <ul>
				  <li><%= link_to 'Entrar', new_property_owner_session_path %></li>
				  <li><%= link_to 'Cadastro como Proprietário', new_property_owner_registration_path %>
			  </ul>
		  <% end %>
	  </nav>
	  <p><%= notice %></p>
	  <p><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/properties/my_properties.html.erb
<% if @properties.empty? %>
	<p>Você ainda não cadastrou imóveis</p>
		<%= link_to 'Cadastre seu imóvel agora', new_property_path %>
<% else %>
	<nav>
		<ul>
			<% @properties.each do | property | %>
				<li>
					<%= link_to property.title, property %>
				</li>
			<% end %>
		</ul>
	</nav>
<% end %>

app/views/properties/new.html.erb
<h1><%= t('.title') %></h1>



<% if @property.errors.any? %>
	<ul>
		<% @property.errors.full_messages.each do |error| %>
			<li> <%= error %> </li>
		<% end %>
	</ul>
<% end %>

<%= form_with(model: @property) do |f| %>
	<div>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div>
		<%= f.label :description%>
		<%= f.text_field :description %>
	</div>
	<div>
		<%= f.label :rooms, 'Quartos' %>
		<%= f.text_field :rooms %>
	</div>
	<div>
		<%= f.label :bathrooms, 'Banheiros' %>
		<%= f.text_field :bathrooms %>
	</div>
	<div>
		<%= f.label :daily_rate, 'Diária' %>
		<%= f.number_field :daily_rate %>
	</div>
	<div>
		<%= f.label :pets, 'Aceita Pets' %>
		<%= f.check_box :pets%>
	</div>
	<div>
		<%= f.label :parking_slot, 'Vaga de Estacionamento' %>
		<%= f.check_box :parking_slot %>
	</div>
	<div>
		<%= f.label :property_type_id, 'Tipo' %>
		<%= f.collection_select :property_type_id, PropertyType.all, :id, :name %>
	</div>
	<div>
		<%= f.label :property_location_id, 'Região' %>
		<%= f.collection_select :property_location_id, PropertyLocation.all, :id, :name %>
	</div>
	<%= f.submit 'Enviar' %>
<% end %>

app/views/properties/show.html.erb
<h1><%= @property.title %></h1>
<p><%= @property.description %></p>
<dl>
	<dt>Quartos:</dt>
	<dd><%= @property.rooms %></dd>
	<dt>Banheiros:</dt>
	<dd><%= @property.bathrooms %></dd>
	<dt>Aceita Pets:</dt>
	<dd><%= @property.pets ? 'Sim' : 'Não' %> </dd>
	<dt>Estacionamento:</dt>
	<dd><%= @property.parking_slot ? 'Sim' : 'Não' %></dd>
	<dt>Diária:</dt>
	<dd><%= number_to_currency(@property.daily_rate) %></dd>
	<dt>Tipo:</dt>
	<dd><%= @property.property_type.name %></dd>
	<dt>Região:</dt>
	<dd><%= @property.property_location.name %></dd>
	<dt>Imóvel de: </dt>
	<dd><%= @property.property_owner.email %></dd>
</dl>

<%= link_to("Voltar", root_path) %>

app/views/property_locations/new.html.erb
<h1>Cadastrar Regiões:</h1>
<%= form_with(model: @location) do |f| %>
	<div>
		<%= f.label :name, 'Nome' %>
		<%= f.text_field :name %>
	</div>
	<%= f.submit 'Enviar' %>
<% end %>
<div>
	<% flash.each do |name, msg| %>
		<%= content_tag :p, msg, class: name %>
	<% end %>
</div>

app/views/property_locations/show.html.erb
<h1>Imóveis da região <%= @property_location.name %> </h1>

<p>
	<% @property_location.properties.each do |property| %>
		<%= link_to property.title, property %>
	<% end %>
</p>

app/views/property_types/new.html.erb
<h1>Cadastrar um novo Tipo de Imóvel</h1>

<%= form_with(model: @property_type) do |f| %>
	<div>
		<%= f.label :name, 'Nome' %>
		<%= f.text_field :name %>
	</div>
	<%= f.submit 'Enviar' %>
<% end %>

<% if @property_type.errors.any? %>
	<ul>
		<% @property_type.errors.full_messages.each do |error| %>
			<li><%= error %></li>
		<% end %>
	</ul>
<% end %>

app/views/property_types/show.html.erb
<h1>Imóveis do tipo <%= @property_type.name %> </h1>

<p>
	<% @property_type.properties.each do |property| %>
		<%= link_to property.title, property %>
	<% end %>
</p>